name: Bot schedule

on:
  schedule:
    - cron: "15 10,20 * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Run bot
        run: docker run ${{ secrets.DOCKERHUB_USER }}/rol-automizer -u ${{ secrets.ROL_USERNAME }} -p ${{ secrets.ROL_PASSWORD }}
